<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

class Lib_ega_booking_type {



   function booking_type($id_tipo_servicio)
   {

       $booking_type = '';

       switch ($id_tipo_servicio) {

             case 'TRAETG' : $booking_type =  3;
             break;
             case 'DEBITO' : $booking_type =  3;
             break;
             case 'AU' : $booking_type =  3;
             break;
             case 'CRAUT0' : $booking_type =  3;
             break;
             case 'GREAUT' : $booking_type =  3;
             break;
             case 'GREAUT-0' : $booking_type =  3;
             break;
             case 'GREBUS' : $booking_type =  3;
             break;
             case 'GREBUS-0' : $booking_type =  3;
             break;
             case 'RENAFR' : $booking_type =  3;
             break;
             case 'RENAT0' : $booking_type =  3;
             break;
             case 'RENAUT' : $booking_type =  3;
             break;
             case 'GTRAER' : $booking_type =  7;
             break;
             case 'GTRAER-0' : $booking_type =  7;
             break;
             case 'TR' : $booking_type =  7;
             break;
             case 'TRAAUA' : $booking_type =  7;
             break;
             case 'TRACAS' : $booking_type =  7;
             break;
             case 'TRAETN' : $booking_type =  7;
             break;
             case 'TRAEXC' : $booking_type =  7;
             break;
             case 'TRAGDN' : $booking_type =  7;
             break;
             case 'TRAGOL' : $booking_type =  7;
             break;
             case 'TRALIZ' : $booking_type =  7;
             break;
             case 'TRANOV' : $booking_type =  7;
             break;
             case 'TRANSP' : $booking_type =  7;
             break;
             case 'TRAPTO' : $booking_type =  7;
             break;
             case 'TRAPTO-T0' : $booking_type =  7;
             break;
             case 'TRASUB' : $booking_type =  7;
             break;
             case 'TRATCE' : $booking_type =  7;
             break;
             case 'TRATOT' : $booking_type =  7;
             break;
             case 'TRATPS' : $booking_type =  7;
             break;
             case 'TRATTE' : $booking_type =  7;
             break;
             case 'CCHA10' : $booking_type =  10;
             break;
             case 'CCHA15' : $booking_type =  10;
             break;
             case 'CCHAT0' : $booking_type =  10;
             break;
             case 'CCRU10' : $booking_type =  10;
             break;
             case 'CCRU15' : $booking_type =  10;
             break;
             case 'CCRUT0' : $booking_type =  10;
             break;
             case 'CGRU10' : $booking_type =  10;
             break;
             case 'CGRU15' : $booking_type =  10;
             break;
             case 'CGRUT0' : $booking_type =  10;
             break;
             case 'CHGDL' : $booking_type =  10;
             break;
             case 'CHMEX' : $booking_type =  10;
             break;
             case 'CHMTY' : $booking_type =  10;
             break;
             case 'CHOT10' : $booking_type =  10;
             break;
             case 'CHOT15' : $booking_type =  10;
             break;
             case 'CHOTT0' : $booking_type =  10;
             break;
             case 'CHSAN' : $booking_type =  10;
             break;
             case 'CHVAL' : $booking_type =  10;
             break;
             case 'COLA10' : $booking_type =  10;
             break;
             case 'COLA15' : $booking_type =  10;
             break;
             case 'COLAT0' : $booking_type =  10;
             break;
             case 'COMBSP' : $booking_type =  10;
             break;
             case 'CRAU10' : $booking_type =  10;
             break;
             case 'CRAU15' : $booking_type =  10;
             break;
             case 'CSEG10' : $booking_type =  10;
             break;
             case 'CSEG15' : $booking_type =  10;
             break;
             case 'CSEGT0' : $booking_type =  10;
             break;
             case 'CTRA10' : $booking_type =  10;
             break;
             case 'CTRA15' : $booking_type =  10;
             break;
             case 'CTRAT0' : $booking_type =  10;
             break;
             case 'GCOCHA' : $booking_type =  10;
             break;
             case 'GCOCHA-0' : $booking_type =  10;
             break;
             case 'GCOCRU' : $booking_type =  10;
             break;
             case 'GCOCRU-0' : $booking_type =  10;
             break;
             case 'GCOHTI-0' : $booking_type =  10;
             break;
             case 'GCOHTN' : $booking_type =  10;
             break;
             case 'GCORAB' : $booking_type =  10;
             break;
             case 'GCORAB-0' : $booking_type =  10;
             break;
             case 'GCORAU' : $booking_type =  10;
             break;
             case 'GCORAU-0' : $booking_type =  10;
             break;
             case 'GCOSEE' : $booking_type =  10;
             break;
             case 'GCOSEE-0' : $booking_type =  10;
             break;
             case 'GCOSEG' : $booking_type =  10;
             break;
             case 'GCOSEG-0' : $booking_type =  10;
             break;
             case 'GCOTAP' : $booking_type =  10;
             break;
             case 'GCOTAP-0' : $booking_type =  10;
             break;
             case 'GCOTTR' : $booking_type =  10;
             break;
             case 'GCOTTR-0' : $booking_type =  10;
             break;
             case 'GCOVIS' : $booking_type =  10;
             break;
             case 'GCOVIS-0' : $booking_type =  10;
             break;
             case 'INGXAF' : $booking_type =  10;
             break;
             case 'OTINGR' : $booking_type =  10;
             break;
             case 'CHMEXAV' : $booking_type =  10;
             break;
             case 'CHMTYAV' : $booking_type =  10;
             break;
             case 'CRUCER' : $booking_type =  4;
             break;
             case 'CRUCER-10' : $booking_type =  4;
             break;
             case 'CRUCER-T0' : $booking_type =  4;
             break;
             case 'GOCRUC' : $booking_type =  4;
             break;
             case 'GOCRUC-0' : $booking_type =  4;
             break;
             case 'NAVCAR' : $booking_type =  4;
             break;
             case 'NAVCAR-FR' : $booking_type =  4;
             break;
             case 'NAVCAR-T0' : $booking_type =  4;
             break;
             case 'NAVCCR' : $booking_type =  4;
             break;
             case 'NAVCCR-FR' : $booking_type =  4;
             break;
             case 'NAVCCR-T0' : $booking_type =  4;
             break;
             case 'NAVCRI' : $booking_type =  4;
             break;
             case 'NAVCRI-FR' : $booking_type =  4;
             break;
             case 'NAVCRI-T0' : $booking_type =  4;
             break;
             case 'NAVMSC' : $booking_type =  4;
             break;
             case 'NAVMSC-FR' : $booking_type =  4;
             break;
             case 'NAVMSC-T0' : $booking_type =  4;
             break;
             case 'NAVNCR' : $booking_type =  4;
             break;
             case 'NAVNCR-FR' : $booking_type =  4;
             break;
             case 'NAVNCR-T0' : $booking_type =  4;
             break;
             case 'NAVOSC' : $booking_type =  4;
             break;
             case 'NAVOSC-FR' : $booking_type =  4;
             break;
             case 'NAVOSC-T0' : $booking_type =  4;
             break;
             case 'NAVPUL' : $booking_type =  4;
             break;
             case 'NAVPUL-FR' : $booking_type =  4;
             break;
             case 'NAVPUL-T0' : $booking_type =  4;
             break;
             case 'NAVRCA' : $booking_type =  4;
             break;
             case 'NAVRCA-FR' : $booking_type =  4;
             break;
             case 'NAVRCA-T0' : $booking_type =  4;
             break;

             
             case 'CSAG' : $booking_type =  9;   
             break;
             case 'CSE' : $booking_type =  9;    
             break;
             case 'CSFAU' : $booking_type =  9; 
             break;
             case 'CSFEX' : $booking_type =  9;
             break;
             case 'CSFHI' : $booking_type =  9;
             break;
             case 'CSFHN' : $booking_type =  9;
             break;
             case 'CSFHX' : $booking_type =  9;
             break;
             case 'CSFLC' : $booking_type =  9;
             break;
             case 'CSFRH' : $booking_type =  9;
             break;
             case 'CSFRV' : $booking_type =  9;
             break;
             case 'CSFVI' : $booking_type =  9;
             break;
             case 'CSFVN' : $booking_type =  9;
             break;
             case 'CSOA' :  $booking_type =  9;
             break;
             case 'CSOEX' : $booking_type =  9;
             break;
             case 'CSOHI' : $booking_type =  9;
             break;
             case 'CSOHN' : $booking_type =  9;
             break;
             case 'CSOHX' : $booking_type =  9;
             break;
             case 'CSOLC' : $booking_type =  9;
             break;
             case 'CSORH' : $booking_type =  9;
             break;
             case 'CSORV' : $booking_type =  9;
             break;
             case 'CSOVI' : $booking_type =  9;
             break;
             case 'CSOVN' : $booking_type =  9;
             break;
             case 'CSSS' : $booking_type =  9;
             break;
             case 'CSVIP' : $booking_type =  9;
             break;
             case 'CSVIS' : $booking_type =  9;
             break;


             case 'CS' : $booking_type =  10;
             break;
             case 'CSFE' : $booking_type =  10;
             break;
             case 'CSSIVA' : $booking_type =  10;
             break;
             case 'CUPONHTL' : $booking_type =  10;
             break;
             case 'FCRU15' : $booking_type =  10;
             break;
             case 'FCRUT0' : $booking_type =  10;
             break;
             case 'FH0T15' : $booking_type =  10;
             break;
             case 'FHOTT0' : $booking_type =  10;
             break;
             case 'FPCH15' : $booking_type =  10;
             break;
             case 'FPCHT0' : $booking_type =  10;
             break;
             case 'FPGR15' : $booking_type =  10;
             break;
             case 'FPGRT0' : $booking_type =  10;
             break;
             case 'FRAU15' : $booking_type =  10;
             break;
             case 'FRAUT0' : $booking_type =  10;
             break;
             case 'FSES15' : $booking_type =  10;
             break;
             case 'FSEST0' : $booking_type =  10;
             break;
             case 'FTRA15' : $booking_type =  10;
             break;
             case 'FTRAT0' : $booking_type =  10;
             break;
             case 'GINGCH' : $booking_type =  10;
             break;
             case 'GINGCH-0' : $booking_type =  10;
             break;
             case 'GINGCR' : $booking_type =  10;
             break;
             case 'GINGCR-0' : $booking_type =  10;
             break;
             case 'GINGCS' : $booking_type =  10;
             break;
             case 'GINGCS-0' : $booking_type =  10;
             break;
             case 'GINGRA' : $booking_type =  10;
             break;
             case 'GINGRA-0' : $booking_type =  10;
             break;
             case 'GINGRH' : $booking_type =  10;
             break;
             case 'GINGRH-0' : $booking_type =  10;
             break;
             case 'GINGSE' : $booking_type =  10;
             break;
             case 'GINGSE-0' : $booking_type =  10;
             break;
             case 'GINGTA' : $booking_type =  10;
             break;
             case 'GINGTA-0' : $booking_type =  10;
             break;
             case 'INGBUS' : $booking_type =  10;
             break;
             case 'INGCSG' : $booking_type =  10;
             break;
             case 'INGXAH' : $booking_type =  10;
             break;
             case 'TRONDEN' : $booking_type =  10;
             break;
             
             case 'GHOTIN-0' : $booking_type =  2;
             break;
             case 'GHOTNA' : $booking_type =  2;
             break;
             case 'HOTINT' : $booking_type =  2;
             break;
             case 'HOTINT-T0' : $booking_type =  2;
             break;
             case 'HOTNAC' : $booking_type =  2;
             break;
             case 'HOTNAC-10' : $booking_type =  2;
             break;
             case 'INGRHG' : $booking_type =  10;
             break;
             case 'SHRP-0' : $booking_type =  10;
             break;
             case 'SISTRE-10' : $booking_type =  10;
             break;
             case 'AUTOBFR' : $booking_type =  10;
             break;
             case 'AUTOBT0' : $booking_type =  10;
             break;
             case 'AUTOBU' : $booking_type =  10;
             break;
             case 'CHR' : $booking_type =  10;
             break;
             case 'CHR-10' : $booking_type =  10;
             break;
             case 'CHR-T0' : $booking_type =  10;
             break;
             case 'COPVIA' : $booking_type =  10;
             break;
             case 'COPVIAFR' : $booking_type =  10;
             break;
             case 'COPVIAT0' : $booking_type =  10;
             break;
             case 'FOPVIA' : $booking_type =  10;
             break;
             case 'FOPVIAT0' : $booking_type =  10;
             break;
             case 'GOVICA' : $booking_type =  10;
             break;
             case 'GOVICA-0' : $booking_type =  10;
             break;
             case 'GPCHAR' : $booking_type =  10;
             break;
             case 'GPCHAR-0' : $booking_type =  10;
             break;
             case 'OPEVIA' : $booking_type =  10;
             break;
             case 'OTROSO' : $booking_type =  10;
             break;
             case 'OTROSO-10' : $booking_type =  10;
             break;
             case 'OTROSO-T0' : $booking_type =  10;
             break;
             case 'OVIAJE' : $booking_type =  10;
             break;
             case 'OVIAJEFR' : $booking_type =  10;
             break;
             case 'OVIAJET0' : $booking_type =  10;
             break;
             case 'VIRTUOSO' : $booking_type =  10;
             break;
             case 'COOPVA' : $booking_type =  10;
             break;
             case 'COOPVAT0' : $booking_type =  10;
             break;
             case 'CHGDLAV' : $booking_type =  10;
             break;  
             case 'TRAVIP' : $booking_type =  5;
             break;  
             case 'CR' : $booking_type =  10;
             break;
             case 'GSEPHR' : $booking_type =  10;
             break;
             case 'GSEPHR-0' : $booking_type =  10;
             break;
             case 'GSERES' : $booking_type =  10;
             break;
             case 'GSERES-0' : $booking_type =  10;
             break;
             case 'INCENTIVOS' : $booking_type =  10;
             break;
             case 'INGUTC' : $booking_type =  10;
             break;
             case 'INGXPCV' : $booking_type =  10;
             break;
             case 'INGXSE' : $booking_type =  10;
             break;
             case 'IVA COMPL' : $booking_type =  10;
             break;
             case 'NCE' : $booking_type =  10;
             break;
             case 'NOTCRE' : $booking_type =  10;
             break;
             case 'OTRING' : $booking_type =  10;
             break;
             case 'OTRING-T0' : $booking_type =  10;
             break;
             case 'PROP' : $booking_type =  10;
             break;
             case 'PS' : $booking_type =  8;
             break;
             case 'SEGLAT' : $booking_type =  8;
             break;
             case 'SEVAR' : $booking_type =  10;
             break;
             case 'SEVAR-11' : $booking_type =  10;
             break;
             case 'SEVAR-T0' : $booking_type =  10;
             break;
             case 'SHRP' : $booking_type =  10;
             break;
             case 'SISTRE' : $booking_type =  10;
             break;
             case 'TRAAIR' : $booking_type =  10;
             break;
             case 'TRAVISA-10' : $booking_type =  10;
             break;
             case 'TRAVISA-T0' : $booking_type =  10;
             break;
             case 'TRVISA' : $booking_type =  10;
             break;
             case 'TVILIZ' : $booking_type =  10;
             break;
             case 'VI' : $booking_type =  10;
             break;
             case 'VTAAF' : $booking_type =  10;
             break;
             case 'NCXREF' : $booking_type =  10;
             break;
             case 'TCTRCO' : $booking_type =  10;
             break;
             case 'SHOOTV' : $booking_type =  10;
             break;
             case 'ANTICIPO' : $booking_type =  10;
             break;
             case 'ASSIST' : $booking_type =  8;
             break;
             case 'ASSIST-T0' : $booking_type =  8;
             break;
             case 'AXASEG' : $booking_type =  8;
             break;
             case 'GOSEGU' : $booking_type =  8;
             break;
             case 'GOSEGU-0' : $booking_type =  8;
             break;
             case 'INGSEG' : $booking_type =  8;
             break;
             case 'INTSEG' : $booking_type =  8;
             break;
             case 'INTSEG-T0' : $booking_type =  8;
             break;
             case 'SEGU-T0' : $booking_type =  8;
             break;
             case 'SEGUFR' : $booking_type =  8;
             break;
             case 'SEGURO' : $booking_type =  8;
             break;
             case 'SEGVIA' : $booking_type =  8;
             break;
             case 'SEGVIA-T0' : $booking_type =  8;
             break;
             case 'WASSIT' : $booking_type =  8;
             break;
             case 'WASSIT-T0' : $booking_type =  8;
             break;
             case 'EURASS' : $booking_type =  8;
             break;
             case 'EURASS-T0' : $booking_type =  8;
             break;
             case 'CTREFR' : $booking_type =  8;
             break;
             case 'CTREN' : $booking_type =  8;
             break;
             case 'CTRET0' : $booking_type =  8;
             break;
             case 'GOTREN' : $booking_type =  8;
             break;
             case 'GOTREN-0' : $booking_type =  8;
             break;
             case 'TRENFR' : $booking_type =  8;
             break;
             case 'TRENSE' : $booking_type =  8;
             break;
             case 'TRENT0' : $booking_type =  8;
             break;
             case 'BD' : $booking_type =  1;
             break;
             case 'BI' : $booking_type =  1;
             break;
             case '12345' : $booking_type =  10;
             break;
             case 'ACALAFIA' : $booking_type =  10;
             break;
             case 'AN' : $booking_type =  10;
             break;
             case 'BSP' : $booking_type =  10;
             break;
             case 'BSU' : $booking_type =  10;
             break;
             case 'CALAFIA' : $booking_type =  10;
             break;
             case 'CALAFIAFR' : $booking_type =  10;
             break;
             case 'GLABSP' : $booking_type =  10;
             break;
             case 'GLABSP-0' : $booking_type =  10;
             break;
             case 'GOLABC' : $booking_type =  10;
             break;
             case 'GOLABC-0' : $booking_type =  10;
             break;
             case 'LABC' : $booking_type =  10;
             break;
             case 'LAFBSP' : $booking_type =  10;
             break;
             case 'LK' : $booking_type =  10;
             break;
             case 'OTOPLA' : $booking_type =  10;
             break;
             case 'OTOPLA-T0' : $booking_type =  10;
             break;
             case 'OTLABC' : $booking_type =  10;
             break;
             case 'OTLABC-T0' : $booking_type =  10;
             break;
             case 'AI' : $booking_type =  10;
             break;
             case 'AD' : $booking_type =  10;
             break; 


      }
 
      if($booking_type == ''){

            $booking_type = 10;

      }

      return $booking_type;

      
   }


   
}