<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

class Lib_ciudades_pais_convert {

   function pais($cod_pais)
   {


    $PAIS = '';

  switch ($cod_pais) {
      
      case 'AF':  $PAIS =  'AFG';
      break;
      case 'AX':  $PAIS =  'ALA';
      break;
      case 'AL':  $PAIS =  'ALB';
      break;
      case 'DE':  $PAIS =  'DEU';
      break;
      case 'AD':  $PAIS =  'AND';
      break;
      case 'AO':  $PAIS =  'AGO';
      break;
      case 'AI':  $PAIS =  'AIA';
      break;
      case 'AQ':  $PAIS =  'ATA';
      break;
      case 'AG':  $PAIS =  'ATG';
      break;
      case 'AN':  $PAIS =  'ANT';
      break;
      case 'SA':  $PAIS =  'SAU';
      break;
      case 'DZ':  $PAIS =  'DZA';
      break;
      case 'AR':  $PAIS =  'ARG';
      break;
      case 'AM':  $PAIS =  'ARM';
      break;
      case 'AW':  $PAIS =  'ABW';
      break;
      case 'AU':  $PAIS =  'AUS';
      break;
      case 'AT':  $PAIS =  'AUT';
      break;
      case 'AZ':  $PAIS =  'AZE';
      break;
      case 'BS':  $PAIS =  'BHS';
      break;
      case 'BH':  $PAIS =  'BHR';
      break;
      case 'BD':  $PAIS =  'BGD';
      break;
      case 'BB':  $PAIS =  'BRB';
      break;
      case 'BY':  $PAIS =  'BLR';
      break;
      case 'BE':  $PAIS =  'BEL';
      break;
      case 'BZ':  $PAIS =  'BLZ';
      break;
      case 'BJ':  $PAIS =  'BEN';
      break;
      case 'BM':  $PAIS =  'BMU';
      break;
      case 'BT':  $PAIS =  'BTN';
      break;
      case 'BO':  $PAIS =  'BOL';
      break;
      case 'BA':  $PAIS =  'BIH';
      break;
      case 'BW':  $PAIS =  'BWA';
      break;
      case 'BV':  $PAIS =  'BVT';
      break;
      case 'BR':  $PAIS =  'BRA';
      break;
      case 'BN':  $PAIS =  'BRN';
      break;
      case 'BG':  $PAIS =  'BGR';
      break;
      case 'BF':  $PAIS =  'BFA';
      break;
      case 'BI':  $PAIS =  'BDI';
      break;
      case 'CV':  $PAIS =  'CPV';
      break;
      case 'KY':  $PAIS =  'CYM';
      break;
      case 'KH':  $PAIS =  'KHM';
      break;
      case 'CM':  $PAIS =  'CMR';
      break;
      case 'CA':  $PAIS =  'CAN';
      break;
      case 'CF':  $PAIS =  'CAF';
      break;
      case 'TD':  $PAIS =  'TCD';
      break;
      case 'CZ':  $PAIS =  'CZE';
      break;
      case 'CL':  $PAIS =  'CHL';
      break;
      case 'CN':  $PAIS =  'CHN';
      break;
      case 'CY':  $PAIS =  'CYP';
      break;
      case 'CC':  $PAIS =  'CCK';
      break;
      case 'CO':  $PAIS =  'COL';
      break;
      case 'KM':  $PAIS =  'COM';
      break;
      case 'CG':  $PAIS =  'COG';
      break;
      case 'CD':  $PAIS =  'COD';
      break;
      case 'CK':  $PAIS =  'COK';
      break;
      case 'KP':  $PAIS =  'PRK';
      break;
      case 'KR':  $PAIS =  'KOR';
      break;
      case 'CI':  $PAIS =  'CIV';
      break;
      case 'CR':  $PAIS =  'CRI';
      break;
      case 'HR':  $PAIS =  'HRV';
      break;
      case 'CU':  $PAIS =  'CUB';
      break;
      case 'DK':  $PAIS =  'DNK';
      break;
      case 'DM':  $PAIS =  'DMA';
      break;
      case 'DO':  $PAIS =  'DOM';
      break;
      case 'EC':  $PAIS =  'ECU';
      break;
      case 'EG':  $PAIS =  'EGY';
      break;
      case 'SV':  $PAIS =  'SLV';
      break;
      case 'AE':  $PAIS =  'ARE';
      break;
      case 'ER':  $PAIS =  'ERI';
      break;
      case 'SK':  $PAIS =  'SVK';
      break;
      case 'SI':  $PAIS =  'SVN';
      break;
      case 'ES':  $PAIS =  'ESP';
      break;
      case 'EA':  $PAIS =  'ESP';
      break;
      case 'US':  $PAIS =  'USA';
      break;
      case 'UM':  $PAIS =  'UMI';
      break;
      case 'EE':  $PAIS =  'EST';
      break;
      case 'ET':  $PAIS =  'ETH';
      break;
      case 'FO':  $PAIS =  'FRO';
      break;
      case 'PH':  $PAIS =  'PHL';
      break;
      case 'FI':  $PAIS =  'FIN';
      break;
      case 'FJ':  $PAIS =  'FJI';
      break;
      case 'FR':  $PAIS =  'FRA';
      break;
      case 'GA':  $PAIS =  'GAB';
      break;
      case 'GM':  $PAIS =  'GMB';
      break;
      case 'GE':  $PAIS =  'GEO';
      break;
      case 'GS':  $PAIS =  'SGS';
      break;
      case 'GH':  $PAIS =  'GHA';
      break;
      case 'GI':  $PAIS =  'GIB';
      break;
      case 'GD':  $PAIS =  'GRD';
      break;
      case 'GR':  $PAIS =  'GRC';
      break;
      case 'GL':  $PAIS =  'GRL';
      break;
      case 'GP':  $PAIS =  'GLP';
      break;
      case 'GU':  $PAIS =  'GUM';
      break;
      case 'GT':  $PAIS =  'GTM';
      break;
      case 'GF':  $PAIS =  'GUF';
      break;
      case 'GG':  $PAIS =  'GGY';
      break;
      case 'GN':  $PAIS =  'GIN';
      break;
      case 'GQ':  $PAIS =  'GNQ';
      break;
      case 'GW':  $PAIS =  'GNB';
      break;
      case 'GY':  $PAIS =  'GUY';
      break;
      case 'HT':  $PAIS =  'HTI';
      break;
      case 'HM':  $PAIS =  'HMD';
      break;
      case 'HN':  $PAIS =  'HND';
      break;
      case 'HK':  $PAIS =  'HKG';
      break;
      case 'HU':  $PAIS =  'HUN';
      break;
      case 'IN':  $PAIS =  'IND';
      break;
      case 'ID':  $PAIS =  'IDN';
      break;
      case 'IR':  $PAIS =  'IRN';
      break;
      case 'IQ':  $PAIS =  'IRQ';
      break;
      case 'IE':  $PAIS =  'IRL';
      break;
      case 'IS':  $PAIS =  'ISL';
      break;
      case 'IL':  $PAIS =  'ISR';
      break;
      case 'IT':  $PAIS =  'ITA';
      break;
      case 'JM':  $PAIS =  'JAM';
      break;
      case 'JP':  $PAIS =  'JPN';
      break;
      case 'JE':  $PAIS =  'JEY';
      break;
      case 'JO':  $PAIS =  'JOR';
      break;
      case 'KZ':  $PAIS =  'KAZ';
      break;
      case 'KE':  $PAIS =  'KEN';
      break;
      case 'KG':  $PAIS =  'KGZ';
      break;
      case 'KI':  $PAIS =  'KIR';
      break;
      case 'KW':  $PAIS =  'KWT';
      break;
      case 'LA':  $PAIS =  'LAO';
      break;
      case 'LS':  $PAIS =  'LSO';
      break;
      case 'LV':  $PAIS =  'LVA';
      break;
      case 'LB':  $PAIS =  'LBN';
      break;
      case 'LR':  $PAIS =  'LBR';
      break;
      case 'LY':  $PAIS =  'LBY';
      break;
      case 'LI':  $PAIS =  'LIE';
      break;
      case 'LT':  $PAIS =  'LTU';
      break;
      case 'LU':  $PAIS =  'LUX';
      break;
      case 'MO':  $PAIS =  'MAC';
      break;
      case 'MK':  $PAIS =  'MKD';
      break;
      case 'MG':  $PAIS =  'MDG';
      break;
      case 'MY':  $PAIS =  'MYS';
      break;
      case 'MW':  $PAIS =  'MWI';
      break;
      case 'MV':  $PAIS =  'MDV';
      break;
      case 'ML':  $PAIS =  'MLI';
      break;
      case 'MT':  $PAIS =  'MLT';
      break;
      case 'FK':  $PAIS =  'FLK';
      break;
      case 'IM':  $PAIS =  'IMN';
      break;
      case 'MP':  $PAIS =  'MNP';
      break;
      case 'MA':  $PAIS =  'MAR';
      break;
      case 'MH':  $PAIS =  'MHL';
      break;
      case 'MQ':  $PAIS =  'MTQ';
      break;
      case 'MU':  $PAIS =  'MUS';
      break;
      case 'MR':  $PAIS =  'MRT';
      break;
      case 'YT':  $PAIS =  'MYT';
      break;
      case 'MX':  $PAIS =  'MEX';
      break;
      case 'FM':  $PAIS =  'FSM';
      break;
      case 'MD':  $PAIS =  'MDA';
      break;
      case 'MC':  $PAIS =  'MCO';
      break;
      case 'MN':  $PAIS =  'MNG';
      break;
      case 'ME':  $PAIS =  'MNE';
      break;
      case 'MS':  $PAIS =  'MSR';
      break;
      case 'MZ':  $PAIS =  'MOZ';
      break;
      case 'MM':  $PAIS =  'MMR';
      break;
      case 'NA':  $PAIS =  'NAM';
      break;
      case 'NR':  $PAIS =  'NRU';
      break;
      case 'CX':  $PAIS =  'CXR';
      break;
      case 'NP':  $PAIS =  'NPL';
      break;
      case 'NI':  $PAIS =  'NIC';
      break;
      case 'NE':  $PAIS =  'NER';
      break;
      case 'NG':  $PAIS =  'NGA';
      break;
      case 'NU':  $PAIS =  'NIU';
      break;
      case 'NF':  $PAIS =  'NFK';
      break;
      case 'NO':  $PAIS =  'NOR';
      break;
      case 'NC':  $PAIS =  'NCL';
      break;
      case 'NZ':  $PAIS =  'NZL';
      break;
      case 'OM':  $PAIS =  'OMN';
      break;
      case 'NL':  $PAIS =  'NLD';
      break;
      case 'PK':  $PAIS =  'PAK';
      break;
      case 'PW':  $PAIS =  'PLW';
      break;
      case 'PS':  $PAIS =  'PSE';
      break;
      case 'PA':  $PAIS =  'PAN';
      break;
      case 'PG':  $PAIS =  'PNG';
      break;
      case 'PY':  $PAIS =  'PRY';
      break;
      case 'PE':  $PAIS =  'PER';
      break;
      case 'PN':  $PAIS =  'PCN';
      break;
      case 'PF':  $PAIS =  'PYF';
      break;
      case 'PL':  $PAIS =  'POL';
      break;
      case 'PT':  $PAIS =  'PRT';
      break;
      case 'PR':  $PAIS =  'PRI';
      break;
      case 'QA':  $PAIS =  'QAT';
      break;
      case 'GB':  $PAIS =  'GBR';
      break;
      case 'RE':  $PAIS =  'REU';
      break;
      case 'RW':  $PAIS =  'RWA';
      break;
      case 'RO':  $PAIS =  'ROU';
      break;
      case 'RU':  $PAIS =  'RUS';
      break;
      case 'EH':  $PAIS =  'ESH';
      break;
      case 'SB':  $PAIS =  'SLB';
      break;
      case 'WS':  $PAIS =  'WSM';
      break;
      case 'AS':  $PAIS =  'ASM';
      break;
      case 'KN':  $PAIS =  'KNA';
      break;
      case 'SM':  $PAIS =  'SMR';
      break;
      case 'PM':  $PAIS =  'SPM';
      break;
      case 'VC':  $PAIS =  'VCT';
      break;
      case 'SH':  $PAIS =  'SHN';
      break;
      case 'LC':  $PAIS =  'LCA';
      break;
      case 'ST':  $PAIS =  'STP';
      break;
      case 'SN':  $PAIS =  'SEN';
      break;
      case 'RS':  $PAIS =  'SRB';
      break;
      case 'SC':  $PAIS =  'SYC';
      break;
      case 'SL':  $PAIS =  'SLE';
      break;
      case 'SG':  $PAIS =  'SGP';
      break;
      case 'SY':  $PAIS =  'SYR';
      break;
      case 'SO':  $PAIS =  'SOM';
      break;
      case 'LK':  $PAIS =  'LKA';
      break;
      case 'SZ':  $PAIS =  'SWZ';
      break;
      case 'ZA':  $PAIS =  'ZAF';
      break;
      case 'SD':  $PAIS =  'SDN';
      break;
      case 'SE':  $PAIS =  'SWE';
      break;
      case 'CH':  $PAIS =  'CHE';
      break;
      case 'SR':  $PAIS =  'SUR';
      break;
      case 'SJ':  $PAIS =  'SJM';
      break;
      case 'TH':  $PAIS =  'THA';
      break;
      case 'TW':  $PAIS =  'TWN';
      break;
      case 'TZ':  $PAIS =  'TZA';
      break;
      case 'TJ':  $PAIS =  'TJK';
      break;
      case 'IO':  $PAIS =  'IOT';
      break;
      case 'TF':  $PAIS =  'ATF';
      break;
      case 'TL':  $PAIS =  'TLS';
      break;
      case 'TG':  $PAIS =  'TGO';
      break;
      case 'TK':  $PAIS =  'TKL';
      break;
      case 'TO':  $PAIS =  'TON';
      break;
      case 'TT':  $PAIS =  'TTO';
      break;
      case 'TN':  $PAIS =  'TUN';
      break;
      case 'TC':  $PAIS =  'TCA';
      break;
      case 'TM':  $PAIS =  'TKM';
      break;
      case 'TR':  $PAIS =  'TUR';
      break;
      case 'TV':  $PAIS =  'TUV';
      break;
      case 'UA':  $PAIS =  'UKR';
      break;
      case 'UG':  $PAIS =  'UGA';
      break;
      case 'UY':  $PAIS =  'URY';
      break;
      case 'UZ':  $PAIS =  'UZB';
      break;
      case 'VU':  $PAIS =  'VUT';
      break;
      case 'VA':  $PAIS =  'VAT';
      break;
      case 'VE':  $PAIS =  'VEN';
      break;
      case 'VN':  $PAIS =  'VNM';
      break;
      case 'VG':  $PAIS =  'VGB';
      break;
      case 'VI':  $PAIS =  'VIR';
      break;
      case 'WF':  $PAIS =  'WLF';
      break;
      case 'YE':  $PAIS =  'YEM';
      break;
      case 'DJ':  $PAIS =  'DJI';
      break;
      case 'ZM':  $PAIS =  'ZMB';
      break;
      case 'ZW':  $PAIS =  'ZWE';
      break;

     
     
    }

  

    return $PAIS;  //codigo 2 carecteres


   }


   
}